metadata:
 '@modelVersion': 1.1.0
 groupId: flux
 artifactId: rabbitmq-action
 versioning:
  latest: 1.0.1
  release: 1.0.1
  versions:
   version:
   - 1.0.0
   - 1.0.1
  lastUpdated: '20110815133150'

