metadata:
 groupId: org.skife.config
 artifactId: config-magic
 versioning:
  latest: '0.17'
  release: '0.17'
  versions:
   version:
   - '0.4'
   - '0.5'
   - '0.6'
   - '0.7'
   - '0.8'
   - '0.9'
   - '0.11'
   - '0.12'
   - '0.13'
   - '0.14'
   - '0.15'
   - '0.17'
  lastUpdated: '20130312222118'

