metadata:
 groupId: org.apache.geronimo.configs
 artifactId: openjpa2
 versioning:
  latest: 3.0.1
  release: 3.0.1
  versions:
   version:
   - 2.1.3-beta
   - 2.2-beta
   - 3.0-beta-1
   - 3.0-M1
   - 3.0.0
   - 3.0.1
  lastUpdated: '20130526084612'

