metadata:
 groupId: org.commonjava.aprox.docker
 artifactId: aprox-docker-utils
 versioning:
  latest: 0.22.0-1
  release: 0.22.0-1
  versions:
   version:
   - 0.19.1
   - 0.19.1-1
   - 0.19.1-2
   - 0.19.1-3
   - 0.19.2-1
   - 0.19.2-2
   - 0.19.2-3
   - 0.22.0-1
  lastUpdated: '20150626032128'

