metadata:
 groupId: org.jbundle.config
 artifactId: jbundle-project
 versioning:
  latest: 1.0.9
  release: 1.0.9
  versions:
   version:
   - 0.7.7
   - 0.7.8
   - 1.0.1
   - 1.0.2
   - 1.0.3
   - 1.0.4
   - 1.0.5
   - 1.0.6
   - 1.0.7
   - 1.0.9
  lastUpdated: '20150103014028'

