metadata:
 groupId: org.pistoiaalliance.helm
 artifactId: helm2-notationtoolkit
 versioning:
  latest: 1.3.0
  release: 1.3.0
  versions:
   version:
   - 1.0.0
   - 1.1.0
   - 1.2.0
   - 1.3.0
  lastUpdated: '20170418071758'

