metadata:
 groupId: org.arquillian.cube
 artifactId: ftest-docker-compose-v2-git-context
 versioning:
  latest: 1.0.0.Alpha17
  release: 1.0.0.Alpha17
  versions:
   version:
   - 1.0.0.Alpha16
   - 1.0.0.Alpha17
  lastUpdated: '20170201135026'

