metadata:
 groupId: org.pistoiaalliance.helm
 artifactId: helm2-webservice
 versioning:
  latest: 2.1.0
  release: 2.1.0
  versions:
   version:
   - 1.0.0
   - 1.1.0
   - 2.0.0
   - 2.1.0
  lastUpdated: '20170331132831'

