metadata:
 groupId: org.jboss.spec.javax.enterprise.deploy
 artifactId: jboss-jad-api_1.2_spec
 versioning:
  latest: 1.0.1.Final
  release: 1.0.1.Final
  versions:
   version:
   - 1.0.0.Beta1
   - 1.0.0.Final
   - 1.0.1.Final
  lastUpdated: '20120319020327'

