metadata:
 groupId: com.appcrossings.config
 artifactId: appconfig-service
 versioning:
  latest: 1.1.0
  release: 1.1.0
  versions:
   version:
   - 1.0.0
   - 1.0.1
   - 1.1.0
  lastUpdated: '20160715233337'

