metadata:
 groupId: org.jaylib.scala.config
 artifactId: configbase_2.10
 versioning:
  latest: 1.2.0
  release: 1.2.0
  versions:
   version:
   - 1.0.0
   - 1.0.1
   - 1.0.2
   - 1.0.3
   - 1.0.4
   - 1.2.0
  lastUpdated: '20151225092023'

