metadata:
 groupId: org.jbundle.config.web
 artifactId: jbundle-config-web-webapp
 versioning:
  latest: 0.7.8
  release: 0.7.8
  versions:
   version:
   - 0.7.7
   - 0.7.8
  lastUpdated: '20110913062128'

