metadata:
 groupId: org.hawkular.inventory
 artifactId: inventory-impl-tinkerpop
 versioning:
  latest: 0.2.0.Alpha2
  release: 0.2.0.Alpha2
  versions:
   version:
   - 0.0.5
   - 0.0.6
   - 0.0.7
   - 0.0.8
   - 0.0.9
   - 0.1.0.Alpha1
   - 0.1.0.Alpha2
   - 0.1.0.Alpha3
   - 0.1.0.Final
   - 0.2.0.Alpha1
   - 0.2.0.Alpha2
  lastUpdated: '20150722204900'

