metadata:
 groupId: org.everit.config
 artifactId: org.everit.config.conventions
 versioning:
  latest: 9.1.1
  release: 9.1.1
  versions:
   version:
   - 8.0.0
   - 8.0.1
   - 8.0.2
   - 9.0.0
   - 9.0.1
   - 9.0.2
   - 9.0.3
   - 9.0.4
   - 9.0.5
   - 9.0.6
   - 9.0.7
   - 9.0.8
   - 9.1.0
   - 9.1.1
  lastUpdated: '20170102210909'

