metadata:
 groupId: org.xowl.infra
 artifactId: xowl-lang
 versioning:
  latest: 2.0.0
  release: 2.0.0
  versions:
   version:
   - 1.0-beta2
   - 1.0-beta3
   - 1.0-beta4
   - 1.0-beta5
   - 1.0-beta6
   - 1.0-beta7
   - 1.0-beta8
   - 1.0-beta9
   - 1.0.0
   - 1.0.1
   - 1.0.2
   - 2.0.0
  lastUpdated: '20170321195155'

