metadata:
 groupId: org.jbundle.config
 artifactId: org.jbundle.config.archetype
 versioning:
  latest: 0.7.8
  release: 0.7.8
  versions:
   version:
   - 0.7.7
   - 0.7.8
  lastUpdated: '20110913062130'

