metadata:
 groupId: org.apache.geronimo.configs
 artifactId: dojo-jetty
 versioning:
  latest: 3.0-M1
  release: 3.0-M1
  versions:
   version:
   - 1.2-beta
   - '2.2'
   - 2.2.1
   - 3.0-M1
  lastUpdated: '20101211142143'

