metadata:
 groupId: org.jbundle.config
 artifactId: jbundle-artifacts
 versioning:
  latest: 1.4.0
  release: 1.4.0
  versions:
   version:
   - 1.2.6
   - 1.2.7
   - 1.2.8
   - 1.3.0
   - 1.3.5
   - 1.3.6
   - 1.3.7
   - 1.3.8
   - 1.4.0
  lastUpdated: '20150103130857'

