metadata:
 groupId: org.apache.geronimo.configs
 artifactId: dojo-tomcat
 versioning:
  latest: 3.0-M1
  release: 3.0-M1
  versions:
   version:
   - 1.2-beta
   - 2.0.1
   - 2.0.2
   - '2.1'
   - 2.1.1
   - 2.1.2
   - 2.1.3
   - 2.1.4
   - 2.1.5
   - 2.1.6
   - 2.1.7
   - 2.1.8
   - '2.2'
   - 2.2.1
   - 3.0-M1
  lastUpdated: '20111228115708'

