metadata:
 groupId: org.lyranthe.prometheus
 artifactId: play24_2.11
 versioning:
  latest: 0.8.4
  release: 0.8.4
  versions:
   version:
   - 0.7.0
   - 0.8.0
   - 0.8.1
   - 0.8.2
   - 0.8.3
   - 0.8.4
  lastUpdated: '20170104115957'

