metadata:
 groupId: org.apache.geronimo.configs
 artifactId: server-security-config
 versioning:
  latest: 2.0.2
  release: 2.0.2
  versions:
   version:
   - 2.0.1
   - 2.0.2
  lastUpdated: '20101014052627'

