metadata:
 groupId: org.everit.config
 artifactId: org.everit.config.main
 versioning:
  latest: 8.3.0
  release: 8.3.0
  versions:
   version:
   - 6.0.0
   - 6.0.1
   - 6.0.2
   - 7.0.0
   - 7.0.1
   - 7.0.2
   - 7.0.3
   - 7.0.4
   - 7.0.5
   - 7.0.6
   - 7.0.7
   - 7.0.8
   - 8.0.0
   - 8.1.0
   - 8.2.0
   - 8.3.0
  lastUpdated: '20170102211223'

