metadata:
 groupId: org.skife.com.typesafe.config
 artifactId: typesafe-config
 versioning:
  latest: 0.3.0
  release: 0.3.0
  versions:
   version:
   - 0.2.1
   - 0.3.0
  lastUpdated: '20120320213750'

