metadata:
 groupId: de.galan
 artifactId: flux
 versioning:
  latest: 0.7.5
  release: 0.7.5
  versions:
   version:
   - 0.7.0
   - 0.7.1
   - 0.7.2
   - 0.7.3
   - 0.7.4
   - 0.7.5
  lastUpdated: '20160109164154'

