metadata:
 groupId: org.apache.geronimo.configs
 artifactId: jetty8-clustering-wadi
 versioning:
  latest: 3.0.1
  release: 3.0.1
  versions:
   version:
   - 3.0-beta-1
   - 3.0-M1
   - 3.0.0
   - 3.0.1
  lastUpdated: '20130526084627'

