metadata:
 groupId: org.jbundle.javafx.config
 artifactId: org.jbundle.base.screen.view.javafx
 versioning:
  latest: 1.0.3
  release: 1.0.3
  versions:
   version:
   - 1.0.1
   - 1.0.2
   - 1.0.3
  lastUpdated: '20150103014122'

