metadata:
 groupId: org.jbundle.javafx.config
 artifactId: jbundle-view-javafx-reactor
 versioning:
  latest: 1.0.3
  release: 1.0.3
  versions:
   version:
   - 0.9.0
   - 1.0.0.1
   - 1.0.1
   - 1.0.2
   - 1.0.3
  lastUpdated: '20150103014121'

