metadata:
 groupId: org.jbundle.config.dep
 artifactId: jbundle-config-dep-thin-db
 versioning:
  latest: 1.0.9
  release: 1.0.9
  versions:
   version:
   - 1.0.1
   - 1.0.2
   - 1.0.3
   - 1.0.9
  lastUpdated: '20150103014026'

