metadata:
 groupId: hu.meza.tools
 artifactId: config
 versioning:
  latest: 1.1.0
  release: 1.1.0
  versions:
   version:
   - '0.1'
   - 0.1.1
   - 0.1.2
   - 0.2.0
   - 0.3.0
   - 1.0.0
   - 1.0.1
   - 1.0.2
   - 1.1.0
  lastUpdated: '20140227113551'

