metadata:
 groupId: org.jaylib.scala.config
 artifactId: configmacros_2.11
 versioning:
  latest: 1.2.0
  release: 1.2.0
  versions:
   version:
   - 1.1.0
   - 1.2.0
  lastUpdated: '20151224210104'

