metadata:
 groupId: org.apache.geronimo.configs
 artifactId: jetty6-deployer
 versioning:
  latest: 2.2.1
  release: 2.2.1
  versions:
   version:
   - 2.0.1
   - 2.0.2
   - '2.1'
   - 2.1.1
   - 2.1.2
   - 2.1.3
   - 2.1.4
   - 2.1.5
   - 2.1.6
   - 2.1.7
   - 2.1.8
   - '2.2'
   - 2.2.1
  lastUpdated: '20111228115707'

