metadata:
 groupId: org.hawkular.agent
 artifactId: prometheus-scraper
 versioning:
  latest: 0.23.0.Final
  release: 0.23.0.Final
  versions:
   version:
   - 0.17.1.Final
   - 0.17.2.Final
   - 0.17.3.Final
   - 0.17.4.Final
   - 0.17.5.Final
   - 0.18.0.Final
   - 0.18.1.Final
   - 0.19.0.Final
   - 0.19.1.Final
   - 0.19.2.Final
   - 0.20.0.Final
   - 0.20.1.Final
   - 0.21.0.Final
   - 0.22.0.Final
   - 0.23.0.Final
  lastUpdated: '20161025162618'

