metadata:
 groupId: io.prometheus
 artifactId: simpleclient_jetty
 versioning:
  latest: 0.0.21
  release: 0.0.21
  versions:
   version:
   - 0.0.15
   - 0.0.17
   - 0.0.18
   - 0.0.19
   - 0.0.20
   - 0.0.21
  lastUpdated: '20170220141356'

